# Generated by Django 2.2.1 on 2019-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_firstname', models.CharField(max_length=10)),
                ('E_lastname', models.CharField(max_length=10)),
                ('E_id', models.IntegerField()),
            ],
        ),
    ]
